language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.0"
    - RACKET_VERSION="7.1"
    - RACKET_VERSION="7.2"
    - RACKET_VERSION="7.3"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
 - raco pkg install --auto macrotypes-lib/
 - raco pkg install --auto macrotypes-example/
 - raco pkg install --auto rackunit-macrotypes-lib/
 - raco pkg install --auto macrotypes-test/
 - raco pkg install --auto turnstile-lib/
 - raco pkg install --auto turnstile-example/
 - raco pkg install --auto turnstile-test/

script:
 - raco test --package macrotypes-test turnstile-test
 - raco setup
